name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v35.5.1
        with:
          files: "*.txt"

      - name: Print changed files
        run: echo "all_changed_files=${{ steps.changed_files.outputs.all_changed_files }}"
