name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  changed_files:
    name: Test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v38
        with:
          files: |
            *.txt

      - name: Print changed files
        run: echo "all_modified_files=${{ steps.changed_files.outputs.all_modified_files }}"
